---
title: "Chapter 12"
author: "kmm"
date: 'Last updated: `r Sys.Date()`'
output:
  html_document:
    theme: flatly
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rethinking)
library(ellipse)
library(tidyverse)
library(cowplot)
```

## Load `reedfrogs`

```{r}
data(reedfrogs)
d <- reedfrogs
```

## m12.1

```{r}
# Make the tank cluster variable
d <- d %>% 
  mutate(tank = 1:nrow(d))

m12.1 <- map2stan(
  alist(
    surv ~ dbinom(density, p),
    logit(p) <- a_tank[tank],
    a_tank[tank] ~ dnorm(0, 5)
  ),
  data = d)
```

## m12.2

```{r}
m12.2 <- map2stan(
  alist(
    surv ~ dbinom(density, p),
    logit(p) <- a_tank[tank],
    a_tank[tank] ~ dnorm(a, sigma),
    a ~ dnorm(0, 1),
    sigma ~ dcauchy(0, 1)
  ),
  data = d,
  iter = 4000,
  chains = 4)

precis(m12.2, depth = 2)
plot(m12.2)
```

## Compare m12.1 and m12.2

```{r}
rethinking::compare(m12.1, m12.2)
```

## Compare posterior medians

```{r}
post <- extract.samples(m12.2)

# Median intercept for each tank
d <- d %>% 
  mutate(propsurv_est = logistic(apply(post$a_tank, 2, median)))

d %>% 
  ggplot() +
  geom_point(aes(x = tank, y = propsurv), color = "blue", size = 2) +
  geom_point(aes(x = tank, y = propsurv_est), color = "black", pch = 1, size = 2) +
  geom_vline(xintercept = c(16.2, 32.4)) +
  geom_hline(yintercept = logistic(median(post$a)), lty = "dashed") +
  scale_x_continuous(breaks = c(1, 16, 32, 48)) +
  scale_y_continuous(breaks = seq(0, 1, by = 0.2)) +
  labs(x = "Tank", y = "Propotion Survival") +
  annotate("text", x = 8, y = 0.05, label = "Small Tanks") +
  annotate("text", x = 24, y = 0.05, label = "Medium Tanks") +
  annotate("text", x = 42, y = 0.05, label = "Large Tanks")
```

## Simulating pools

```{r}
set.seed(238746)

a <- 1.4
sigma <- 1.5
nponds <- 60
ni <- as.integer(rep(c(5, 10, 25, 35), each = 15))
a_pond <- rnorm(nponds, mean = a, sd = sigma)
dsim <- data.frame(
  pond = 1:nponds,
  ni = ni,
  true_a = a_pond
)
dsim$si <- rbinom(nponds,
                  prob = logistic(dsim$true_a),
                  size = dsim$ni)
dsim$p_nopool <- dsim$si / dsim$ni
```

```{r}
m12.3 <- map2stan(
  alist(
    si ~ dbinom(ni, p),
    logit(p) <- a_pond[pond],
    a_pond[pond] ~ dnorm(a, sigma),
    a ~ dnorm(0, 1),
    sigma ~ dcauchy(0, 1)
  ),
  data = dsim,
  iter = 1e4,
  warmup = 1000
)

precis(m12.3, depth = 2)
```

```{r}
estimated.a_pond <- as.numeric(coef(m12.3)[1:60])
dsim$p_partpool <- logistic(estimated.a_pond)
dsim$p_tru <- logistic(dsim$true_a)
```


## Inferred population distribution

```{r}
# 12.6

```

