---
title: "Chapter 14"
author: "kmm"
date: 'Last updated: `r Sys.Date()`'
output:
  html_document:
    theme: flatly
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("rethinking")
library("tidyverse")
library("cowplot")
```

```{r}
data(milk)
d <- milk
d$neocortex.prop <- d$neocortex.perc / 100
d$logmass <- log(d$mass)
```

```{r}
## R code 14.7
# prep data
data_list <- list(
    kcal = d$kcal.per.g,
    neocortex = d$neocortex.prop,
    logmass = d$logmass )

# fit model
m14.3 <- map2stan(
  alist(
    kcal ~ dnorm(mu, sigma),
    mu <- a + bN * neocortex + bM * logmass,
    neocortex ~ dnorm(nu, sigma_N),
    a ~ dnorm(0, 100),
    c(bN,bM) ~ dnorm(0, 10),
    nu ~ dnorm(0.5, 1),
    sigma_N ~ dcauchy(0, 1),
    sigma ~ dcauchy(0, 1)
  ) ,
  data = data_list,
  iter = 1e4,
  chains = 2
)
precis(m14.3)
```

## Complete cases

```{r}
dcc <- d[complete.cases(d$neocortex.prop), ]
data_list_cc <- list(
  kcal = dcc$kcal.per.g,
  neocortex = dcc$neocortex.prop,
  logmass = dcc$logmass)

# fit model
m14.3cc <- map2stan(
  alist(
    kcal ~ dnorm(mu, sigma),
    mu <- a + bN * neocortex + bM * logmass,
    a ~ dnorm(0, 100),
    c(bN,bM) ~ dnorm(0, 10),
    sigma ~ dcauchy(0, 1)
  ),
  data = data_list_cc, iter = 1e4, chains = 2)
precis(m14.3cc)
```

## With linear relationship

```{r}
## R code 14.10
m14.4 <- map2stan(
  alist(
    kcal ~ dnorm(mu, sigma),
    mu <- a + bN * neocortex + bM * logmass,
    neocortex ~ dnorm(nu, sigma_N),
    nu <- a_N + gM * logmass,
    a ~ dnorm(0, 100),
    c(bN,bM,gM) ~ dnorm(0, 10),
    a_N ~ dnorm(0.5, 1),
    sigma_N ~ dcauchy(0, 1),
    sigma ~ dcauchy(0, 1)
  ) ,
  data = data_list, iter = 1e4, chains = 2)
precis(m14.4, depth = 2)
```

## Compares

```{r}
rethinking::compare(m14.3, m14.4)
```

