---
title: "Chapter 8"
author: "kmm"
date: "February 24, 2016"
output:
  html_document:
    theme: flatly
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Metropolis

```{r}
set.seed(10)

num_weeks <- 1e5
positions <- rep(0, num_weeks)
current <- 10
for (i in 1:num_weeks) {
  # record current position
  positions[i] <- current
  
  # flip coin to generate proposal
  proposal <- current + sample(c(-1, 1), size = 1)
  
  # loop around
  if (proposal < 1) proposal <- 10
  if (proposal > 10) proposal <- 1
  
  # move?
  prob_move <- proposal / current
  current <- ifelse(runif(1) < prob_move, proposal, current)
}
ggplot(data.frame(positions = positions[1:200],
                  week = 1:200), aes(week, positions)) +
  geom_line()
ggplot(data.frame(positions), aes(positions)) +
  geom_bar()
```

## Metropolis w/ Arbitrary Populations

```{r}
library(tidyverse)
set.seed(238476)

# Generate islands and populations
n_islands <- 20
pops <- trunc(1e4 * runif(n_islands, 0.1, 10))

num_weeks <- 1e5
positions <- numeric(num_weeks)
current <- sample(n_islands, size = 1)

for (i in 1:num_weeks) {
  # record current position
  positions[i] <- current
  
  # flip coin to generate proposal
  proposal <- sample(n_islands, size = 1)
  
  # move?
  prob_move <- pops[proposal] / pops[current]
  current <- ifelse(runif(1) < prob_move, proposal, current)
}

ggplot(data.frame(positions = positions[1:200],
                  week = 1:200), aes(week, positions)) +
  geom_line()

ggplot(data.frame(positions), aes(positions)) +
  geom_bar() +
  geom_point(data = tibble(x = 1:n_islands, y = pops / max(pops) * max(table(positions))),
             aes(x, y), color = "red") +
  labs(y = "Counts (gray bars)\nRelative Population Size (red dots)", x = "Island")

```


## 8.2

```{r}
library(rethinking)

```

## Solving a binomial

```{r}
library(rethinking)
set.seed(321876)
s <- 200
y <- rbinom(n = 1, size = s, prob = 0.45)
y01 <- c(rep(1, y), rep(0, s - y))
sum(y)

fm_binom <- rethinking::map(
  alist(
    y ~ dbinom(s, p),
    p ~ dbeta(1, 1)
  ),
  data = list(y = y, s = s)
)
precis(fm_binom)

fm_poisson <- rethinking::map(
  alist(
    y01 ~ dpois(lambda),
    log(lambda) ~ a,
    a ~ dnorm(0, 100)
  ),
  data = list(y01 = y01)
)
precis(fm_poisson)
```

